### ISSUE TITLE
webp 图片格式的疑问?

### ISSUE THREAD

**Issue by RtzX** [amfe/article#31]
看完这篇文章,激起了我对图片的兴趣.又找到了一片文章,其中对各种图片格式做了介绍.http://blog.ibireme.com/2015/11/02/mobile_image_benchmark/然后 又去搜了下webp 这个格式. 目前已知的情况是 只有谷歌的chorme 支持? 主要是看了一下,对于native 和H5的话,这个webp貌似是非常好的一种优化了.我们公司也是采用的H5,但是加载比起京东和淘宝还是有很大的差距,一直就想找个解决方案. hybird 我们也采用了. 现在就是webp的话,你们是怎么实现的?不是只有谷歌的才支持吗?thks

**Comment by Tancy** [comment]
- webp格式浏览器默认的支持情况可以参考：http://caniuse.com/#search=webp
- 手淘native已经全部支持webp
- 手淘iOS的webView是有native提供的组件实现，组件负责去下载webp格式图片，然后转码成jpg提供给webview
- webp格式采用是图片文件大小改变，是下载量的问题。加载性能又是另外一个问题。手淘在网路链路上也有很多的优化。

综合下来，你还是需要分析一下比不上手淘的加载性能具体是那个环境，webp格式文件大小的优化大家都相等（当然压缩参数也会有部分差异）。
