### ISSUE TITLE
dpr=2或者等于3的时候，border设置为1px的时候异常

### ISSUE THREAD

**Issue by tonyljl526** [amfe/article#33]
请问下，为什么在dpr=2和3的 iphone手机上面 border 设置为1 的时候显示异常啊？ 比如有个场景是：添加到购物车，加减号的border设置为1px点击的时候会有异常的情况。 是否和 meta设置有关？ content="initial-scale=0.5, maximum-scale=0.5, minimum-scale=0.5, user-scalable=no  都为0.5 和0.3333333的时候 边框会有异常，请问淘宝是怎么解决的呀？

**Comment by airen** [comment]
我们使用flexible库，然后1px的边框不使用rem做为单位。
