### ISSUE TITLE
关于使用Flexible实现手淘H5页面的终端适配的例子没有实现ipad等平板的适配？

### ISSUE THREAD

**Issue by chanyukai** [amfe/article#35]

**Comment by Jinjiang** [comment]
对于针对手机设计的库和页面，我们有个最大宽度判断，比如 iPad 横屏的时候是 1024，默认我们会限制内容在 540，即常规的手机屏幕宽度内容等比缩放到 540 宽，保障阅读体验不会太差

**Comment by chanyukai** [comment]
那么这个flexible框架是不是没有做到判断ipad以上以及桌面的屏幕？因为我把flexible用在自己写的项目上，到放大ipad以上的尺寸的时候，就没有适配了，这个flexible其实是不是主要通过html上的font-size的值来大小，然后其他页面上的所有尺寸采用rem设置？除了字体（那么，还是要用到@media标签）
