### ISSUE TITLE
移动端全屏滑动h5活动解决方案

### ISSUE THREAD

**Issue by howyhuang** [amfe/article#39]
请教下大神，如何解决移动端全屏下子元素的，宽高和布局问题呢？

H5全屏动画展示类的活动页面，比如设计稿750*1334，我怎么设置子元素的大小

我现在用sass计算样式宽高成rem，js来设置html对应的dip和字体大小。
但是全屏活动在ip4小屏幕手机还是不能完美展现，请教大神有什么方法望告知，有尝试百分比来解决或者根据设备整个页面缩放处理，感觉都不是完美···哎 头疼。

**Comment by dd1994** [comment]
用 flexible 啊，很完美啊，我做过好几次活动了

**Comment by 5se7en** [comment]
@dd1994 手淘的这个方案支持横竖屏切换吗？我上次试了一下好像不支持就没深入研究和使用了？

**Comment by 5se7en** [comment]
@dd1994 好像pad也不适用。。。

**Comment by howyhuang** [comment]
@dd1994  我之前活动也都是flexible写的 但是感觉，750*1344的全屏设计稿子，在小屏幕手机不知道怎么处理 还是我写错了，大神可以指点指点么，
我现在宽高都是转换rem，那top要转换还是写成？
.t2 {
  width: 2.373333rem;
  height: 2.933333rem;
  position: absolute;
  right: 0;
  background: url(../images/t2.jpg) no-repeat;
  background-size: 2.373333rem 2.933333rem;
}

[data-dpr="1"] .t2 {
  top: 38.5px;
}

[data-dpr="2"] .t2 {
  top: 77px;
}

[data-dpr="3"] .t2 {
  top: 115.5px;
}

**Comment by 5se7en** [comment]
@howyhuang手淘的这个方案 一般只有在设置字体才会根据dpr不同写样式，其他都转化成rem

**Comment by howyhuang** [comment]
@se7en-1992  好吧谢啦

**Comment by howyhuang** [comment]
@se7en-1992 我用手淘写微信端全屏活动 还是比较恶心的，哎···不知道怎么解决

**Comment by 5se7en** [comment]
@howyhuang 我原来也写一个项目要求也是适配各种机型的全屏效果，如果用rem布局的话但是ipone5和iPhone4宽度相等高度不同，也就是说根元素的font-size相等所以按照设计稿来的话iPhone5下全屏4就肯定有滚轮。4下全屏5下就肯定有留白。

**Comment by howyhuang** [comment]
@se7en-1992  好吧谢了，放弃4了 崩溃了

**Comment by dolymood** [comment]
全屏效果的话，为了满足各个尺寸手机，总是需要有一部分内容是“动态的”，例如说保证顶部和底部的固定，中间部分可以自适应剩余部分，也就意味着顶部和底部在切图的时候是“绝对的”（不管用rem px %等），而中间则是自适应高度的（flex布局，height 100%等方案）。

**Comment by mahavira** [comment]
retina屏的mac电脑可以吗？用flexible的话是data-dpr是等于多少？

**Comment by chesscai** [comment]
https://github.com/chesscai/flexible-adaptive
