### ISSUE TITLE
用flexible设置Meta，页面会闪动

### ISSUE THREAD

**Issue by weishiji** [amfe/article#42]
因为JS动态加载Meta属性，所以初始设置的字体会很大或者很小，然后JS加载后，才会缩放到正常的比例，请问这个是怎么处理的呢？还是文章里有，我没有看到？

**Comment by hingsir** [comment]
> 另外强烈建议对JS做内联处理，在所有资源加载之前执行这个JS。执行这个JS后，会在<html>元素上增加一个data-dpr属性，以及一个font-size样式。JS会根据不同的设备添加不同的data-dpr值，比如说2或者3，同时会给html加上对应的font-size的值，比如说75px。
