### ISSUE TITLE
支不支持webview呢

### ISSUE THREAD

**Issue by xcsweb** [amfe/article#48]
我百度查不到webview支不支持viewport,但是我采用网易的移动端布局的方案在webview中是有问题的，后来直接把网易的url放进去也是有问题的，但是在手机浏览器打开是没有问题的

**Comment by Jinjiang** [comment]
支持
p.s. 这里是团队发表文章的地方，所以谢绝通过开 issue 的方式发起讨论，我这里先关掉了。谢谢
