### ISSUE TITLE
stylus 字体 Vue项目px转rem

### ISSUE THREAD

**Issue by sunyuanfei** [amfe/article#49]
1、新手基础薄弱 文档字体大小根据像素比sess写法能转下stylus语法写下吗  
2、vue项目有快捷方法换算px=>rem

**Comment by xierenyuan** [comment]
postcss-px2rem 这个就可以。

**Comment by sunyuanfei** [comment]
这个问题有点偷懒 sess语法换成stylus语法怎么写
 @mixin font-dpr($font-size){
    font-size: $font-size;

    [data-dpr="2"] & {
        font-size: $font-size * 2;
    }

    [data-dpr="3"] & {
        font-size: $font-size * 3;
    }
}

**Comment by sunyuanfei** [comment]
你说用postcss-px2rem  使用有点复杂网上资料没有理清楚 你有用过postcss-px2rem 吗
