### ISSUE TITLE
flexible源码有些不明白，求大神支招，thanks

### ISSUE THREAD

**Issue by Kico-Yu** [amfe/article#50]
有一些属性的设置感觉根本没有用到，不清楚作用是什么
![_031617_011142_pm](https://cloud.githubusercontent.com/assets/18063262/23982717/2d74e84c-0a4a-11e7-886a-858f302eee9c.jpg)

**Comment by YunyChan** [comment]
就是给提供给你自己开发时调用用的方法，你可以用或者不用
