### ISSUE TITLE
1024*768的设计稿子怎么设置fontsize 与 rem 的转换呢

### ISSUE THREAD

**Issue by shmilyxwx** [amfe/article#55]
说是吧设计稿子分为100份 1a = 7.5px
                                            1rem = 75px
我的设计稿是1024*768的   1a = 10.24px
                                             1rem = 120.4px
是这个样子的吗？

**Comment by fantasthu** [comment]
webpack2.0 打包flexiable直接写多少px 使用plugin  postcss
